#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	PlaySoundFile("mcoutSound.rso");
	while(true)
	{
		if(SensorValue(light)<60)
		{
			nxtDisplayCenteredTextLine(3, "Lalalalalalalala!");
			motor[motorB] = 25;
			motor[motorC] = 25;
			wait1Msec(100);
		}
		else {
			nxtDisplayCenteredTextLine(3, "Ahh!");
			motor[motorB] = -25;
			motor[motorC] = -25;
			wait1Msec(2000);
			motor[motorC] =0;
			motor[motorB] =-25;
			wait1Msec(3300)
		}
	}
}
